# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a38bf3025c0d34fb2d220624a1ead11465cdf0e208d537c546f6cf86a11a75d56e8806314fb99f7f65052258d9e1841a8ed70ee16714f12bc5991e1ee0070d82

test:
  secret_key_base: 26c49479d6a809618e6b771e027053b48d58be9f252f23e14e2319f758f3e9dc10ae308fbe3c852687765c9ecf7721453c2e97d34a1dbacf7d6199d784cd59cd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
